### ISSUE TITLE
Rename login_client methods

### ISSUE THREAD

**Issue by lukaszgarstecki** [leancodepl/flutter_corelibrary#19]
Consider changing login_client api so that it clearly indicates that method returns `Future<T>`. For example `_loginClient.initialize()` requires await so it can be called `initializeAsync` instead.

**Comment by mateuszwojtczak** [comment]
It seems like it's not a common convention in Dart libs

**Comment by Albert221** [comment]
The signature of the `initialize` method clearly indicates that its return type is a `Future<void>`.

Also, appending the _Async_ suffix is not a convention used in Dart/Flutter codebases.

**Comment by lukaszgarstecki** [comment]
But it is cnovention, not a guideline right?

**Comment by mateuszwojtczak** [comment]
`initializeAsync` would be a good idea if there was another method `initialize` that is sync and we wanted to distinguish them
