### ISSUE TITLE
[leancode_lint] `avoid_conditional_hooks` false positive with `HookBuilder` inside `HookWidget`

### ISSUE THREAD

**Issue by RobertOdrowaz** [leancodepl/flutter_corelibrary#284]
`avoid_conditional_hooks` rule reports a false positive if there is conditional `HookBuilder` inside a `HookWidget`. If the containing widget is a `StatelessWidget` everything works fine.

<img width="435" alt="image" src="https://github.com/leancodepl/flutter_corelibrary/assets/9675199/fd2540de-30ec-486d-955c-5af80d1b4ef3">

```dart
class HookBuilderInIfShouldBeOk extends HookWidget {
  const HookBuilderInIfShouldBeOk({super.key});

  @override
  Widget build(BuildContext context) {
    if (Random().nextBool()) {
      return const SizedBox();
    }

    return HookBuilder(
      builder: (context) {
        useState(1);
        return const SizedBox();
      },
    );
  }
}
```

**Comment by shilangyu** [comment]
Turns out I already had an issue for this, completely forgot about it #241
