### ISSUE TITLE
Add web & umbrella credentials storage

### ISSUE THREAD

**Issue by Albert221** [leancodepl/flutter_corelibrary#31]
Create the `CredentialsStorage` implementation for:

* the Web platform that doesn't have a dependency on the `dart:io` or iOS/Android platforms and uses [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) as its backend
* both mobile (iOS/Android) and Web platforms that's just an umbrella for the credentials storage above and the `FlutterSecureCredentialsStorage`. Probably involving [Dart's conditional importing](https://dart.dev/guides/libraries/create-library-packages#conditionally-importing-and-exporting-library-files).

/cc @mchudy @FlowerAlex

**Comment by bartekpacia** [comment]
I think this can be closed as [flutter_secure_storage](https://pub.dev/packages/flutter_secure_storage/versions/5.0.0-beta.5/changelog) is improving its multi-platform support.

also see #32
