### ISSUE TITLE
New lints

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/flutter_corelibrary#46]
[Dart 2.16](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#linter) introduces [a few new lints](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#linter). We should consider adding some/all of them to `leancode_lint`.

@shilangyu @RobertOdrowazLNCD @Albert221

**Comment by shilangyu** [comment]
New/updated lints from 2.15 that we should consider:

- [`literal_only_boolean_expressions`](https://dart-lang.github.io/linter/lints/literal_only_boolean_expressions.html), `while(true){}` is now allowed
- [`unnecessary_constructor_name`](https://dart-lang.github.io/linter/lints/unnecessary_constructor_name.html), new, prevents constructor tear-off abuses

**Comment by shilangyu** [comment]
Final list of new lints in 2.16:

- [`use_decorated_box`](https://dart-lang.github.io/linter/lints/use_decorated_box.html)
- [`sized_box_shrink_expand`](https://dart-lang.github.io/linter/lints/sized_box_shrink_expand.html)
- [`secure_pubspec_urls`](https://dart-lang.github.io/linter/lints/secure_pubspec_urls.html)
- [`no_leading_underscores_for_local_identifiers`](https://dart-lang.github.io/linter/lints/no_leading_underscores_for_local_identifiers.html)
- [`no_leading_underscores_for_library_prefixes`](https://dart-lang.github.io/linter/lints/no_leading_underscores_for_library_prefixes.html)
- [`avoid_final_parameters`](https://dart-lang.github.io/linter/lints/avoid_final_parameters.html)
- [`conditional_uri_does_not_exist`](https://dart-lang.github.io/linter/lints/conditional_uri_does_not_exist.html)
- [`unnecessary_late`](https://dart-lang.github.io/linter/lints/unnecessary_late.html)
