### ISSUE TITLE
Add new dart 2.17 lints

### ISSUE THREAD

**Issue by shilangyu** [leancodepl/flutter_corelibrary#55]
- new [`use_super_parameters`](https://dart-lang.github.io/linter/lints/use_super_parameters.html)
- new [`use_enums`](https://dart-lang.github.io/linter/lints/use_enums.html)
- new [`use_colored_box`](https://dart-lang.github.io/linter/lints/use_colored_box.html)
- marked stable [`null_check_on_nullable_type_parameter`](https://dart-lang.github.io/linter/lints/null_check_on_nullable_type_parameter.html)

**Comment by bartekpacia** [comment]
> new [use_enums](https://dart-lang.github.io/linter/lints/use_enums.html)

I thought Dart only supports primitive enums (I mean, like C)

**Comment by bartekpacia** [comment]
[use_super_parameters](https://dart-lang.github.io/linter/lints/use_super_parameters.html) – awesome & great & ❤️ 

Interesting thing though is that `Key? key` argument is not subjects to analyzer's [dart[unused_element]](https://dart.dev/diagnostics/unused_element) check if it's in a public constructor. See below:

https://user-images.githubusercontent.com/40357511/168321220-daaf73e7-c06e-4a20-adc3-8c74f3043b60.mov

**Comment by shilangyu** [comment]
> Interesting thing though is that Key? key argument is not subject to analyzer's [dart[unused_element]](https://dart.dev/diagnostics/unused_element) lint if it's in a public constructor.

None of the properties are subject to it in public constructors. Analyzer can now detect unused props in private constructors.

**Comment by bartekpacia** [comment]
Ah, right. I didn't bother to drill down deeper :P

[use_enums](https://dart-lang.github.io/linter/lints/use_enums.html) – okay as well
[null_check_on_nullable_type_parameter](https://dart-lang.github.io/linter/lints/null_check_on_nullable_type_parameter.html) – haven't found a single place in 2 medium-sized projects where it'd appear, so I guess OK

**Comment by bartekpacia** [comment]
as for [use_colored_box](https://github.com/leancodepl/flutter_corelibrary/issues/55#issuecomment-1126190048) – it's fixed in dart-lang/linter v1.24.0
