### ISSUE TITLE
Tracking new lints

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/flutter_corelibrary#64]
[dart-lang/linter](https://github.com/dart-lang/linter) has just got [v1.24.0](https://github.com/dart-lang/linter/releases/tag/1.24.0).

### TLDR:

New lints:
- [unnecessary_to_list_in_spreads](https://github.com/dart-lang/linter/blob/master/lib/src/rules/unnecessary_to_list_in_spreads.dart)
- [unnecessary_null_aware_operator_on_extension_on_nullable](https://github.com/dart-lang/linter/blob/master/lib/src/rules/unnecessary_null_aware_operator_on_extension_on_nullable.dart)

Updated lints:
- [use_colored_box](https://dart-lang.github.io/linter/lints/use_colored_box) to not flag nullable colors

**Comment by bartekpacia** [comment]
cc @shilangyu, you like new lints

**Comment by bartekpacia** [comment]
There are some new and fixed lints in [Dart 2.19](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#2190).

**Comment by shilangyu** [comment]
What is the scope of this issue? I don't think it should be indeterminate (it will never get closed). Imo, instead we should have an issue for new lints for 2.18 and then a separate issue for 2.19.

**Comment by bartekpacia** [comment]
yeah that's a good idea

**Comment by bartekpacia** [comment]
superseded by #79 and #80
