### ISSUE TITLE
Do we need `usePostFrameEffect`?

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/flutter_corelibrary#65]
Is this:

```dart
usePostFrameEffect(() {
  callback();
});
```

much better than the vanilla:

```dart
WidgetsBinding.instance.addPostFrameCallback((_) {
  someCallback();
);
```

?

The one (and only?) advantage that I can think of is the possibility to invoke `callback` conditionally by passing keys to `usePostFrameEffect`. I haven't ever encountered a use case for this tho.

**Comment by Albert221** [comment]
This advantage is the key here. Sometimes we need to initialize something or perform an action after first build, when we already have render objects laid out and and states created.

**Comment by bartekpacia** [comment]
Okay, thanks for raising your voices :) 

Let's close this :)
