### ISSUE TITLE
Support `Operation`s in `package:cqrs`

### ISSUE THREAD

**Issue by shilangyu** [leancodepl/flutter_corelibrary#66]
See https://github.com/leancodepl/corelibrary/issues/188 and https://github.com/leancodepl/corelibrary/pull/301.

TL;DR: Operations combine `Query` and `Command` into one.

Implementation wise, as far as I know the prototype should be identical to `Query`. It differs only semantically for us.

Tagging codeowner: @Albert221, if out of time, I am willing to implement this.

**Comment by Albert221** [comment]
It seems like you're in the circle of knowledge of the new `Operation` concept. Please, feel free to address it :)
