### ISSUE TITLE
Consider renaming `CQRS` types to `Cqrs`

### ISSUE THREAD

**Issue by shilangyu** [leancodepl/flutter_corelibrary#67]
In dart, the standard is to not write acronyms in uppercase unless it is only up to 2 letters long (see here: https://dart.dev/guides/language/effective-dart/style#do-capitalize-acronyms-and-abbreviations-longer-than-two-letters-like-words)

Is that something we want to do?

Tagging codeowner: @Albert221, if out of time, I am willing to implement this.

**Comment by Albert221** [comment]
Let's introduce this change as a part of v7.0.0.
