### ISSUE TITLE
Evaluate new lints from Dart 2.18

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/flutter_corelibrary#79]
- new: [`discarded_futures`](https://dart-lang.github.io/linter/lints/discarded_futures.html)
- new: [`unnecessary_to_list_in_spreads`](https://dart-lang.github.io/linter/lints/unnecessary_to_list_in_spreads.html)
- update: `use_colored_box` does not flag nullable colors
- new:  [`unnecessary_null_aware_operator_on_extension_on_nullable`](https://dart-lang.github.io/linter/lints/unnecessary_null_aware_operator_on_extension_on_nullable.html)

[Dart 2.18 changelogs](https://github.com/dart-lang/sdk/blob/main/CHANGELOG.md#2180)

**Comment by shilangyu** [comment]
Updated the post to list new/update lints. This list is not planned to change.
