### ISSUE TITLE
Evaluate new lints from Dart 2.19

### ISSUE THREAD

**Issue by bartekpacia** [leancodepl/flutter_corelibrary#80]
- new: [`collection_methods_unrelated_type`](https://dart-lang.github.io/linter/lints/collection_methods_unrelated_type.html)
- new: [`combinators_ordering`](https://dart-lang.github.io/linter/lints/combinators_ordering.html)
- new: [`dangling_library_doc_comments`](https://dart-lang.github.io/linter/lints/dangling_library_doc_comments.html)
- new: [`enable_null_safety`](https://dart-lang.github.io/linter/lints/enable_null_safety.html)
- new: [`implicit_call_tearoffs`](https://dart-lang.github.io/linter/lints/implicit_call_tearoffs.html)
- new: [`library_annotations`](https://dart-lang.github.io/linter/lints/library_annotations.html)
- new: [`unnecessary_library_directive`](https://dart-lang.github.io/linter/lints/unnecessary_library_directive.html)
- new: [`unreachable_from_main`](https://dart-lang.github.io/linter/lints/unreachable_from_main.html)
- new: [`use_string_in_part_of_directives`](https://dart-lang.github.io/linter/lints/use_string_in_part_of_directives.html)
- changed: [`use_colored_box`](https://dart-lang.github.io/linter/lints/use_colored_box.html) and [`use_decorated_box`](https://dart-lang.github.io/linter/lints/use_decorated_box.html) to not over-report on containers without a child.

**Comment by bartekpacia** [comment]
FIxed by #82.

**Comment by shilangyu** [comment]
Updated the post to list new/update lints. This list is not planned to change.
