### ISSUE TITLE
Stop depending on `flutter_lints` in `leancode_lints`

### ISSUE THREAD

**Issue by shilangyu** [leancodepl/flutter_corelibrary#98]
The initial idea was to base our lints on `flutter_lints` to be compatible with community standards. But this has long stopped being the case. We now patch `flutter_lints` instead of extending it. For example we disable the `use_build_context_synchronously` rule since we deemed it too restrictive.

I suggest we drop `flutter_lints` completely and just maintain our own set of rules. One less dependency also means we don't have to be wary of upgrading `flutter_lints` in fear that it might introduce/disable some unwanted/wanted rules.

**Comment by bartekpacia** [comment]
Is it possible to depend on `flutter_lints`, but still disable and enable specific lints?

I think that'd make `leancode_lint` easier to maintain.

**Comment by bartekpacia** [comment]
And as for us disabling `use_build_context_synchronously` – I think it got a slew of improvements in the past months. Might be worth checking it out again.

**Comment by shilangyu** [comment]
> Is it possible to depend on `flutter_lints`, but still disable and enable specific lints?
> 
> I think that'd make `leancode_lint` easier to maintain.

thats what we are currently doing, patching `flutter_lints`

**Comment by bartekpacia** [comment]
[Looks like](https://github.com/leancodepl/flutter_corelibrary/blob/master/packages/leancode_lint/lib/analysis_options.yaml) we're 99% extending `flutter_lints` (extending = enabling rules that are not enabled in flutter_lints), and 1% patching it (patching = disabling rules that are enabled by `flutter_lints`)

I think it would make sense to not depend on `flutter_lints` if we disabled many more rules. OTOH, [`flutter_lints`](https://github.com/flutter/packages/blob/main/packages/flutter_lints/lib/flutter.yaml) are very small. I don't have any strong opinion on this topic.
